name: Build and Deploy Node App

on:
    push:
        branches:
            master

jobs:
    build-and-deply:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - uses: actions/setup-node@v3
              with:
                node-version: '20'

            - name: Build Docker Image
              run: | 
                docker build -t vinit1809/linkedin-scraper-be:latest . -f Dockerfile

            - name: Push Docker image to Docker Hub
              run: |
                docker login -u "${{ secrets.DOCKER_HUB_USERNAME}}" --password-stdin
                 docker push vinit1809/linkedin-scraper-be:latest
            
            - name: Deploy to EC2
              env: 
                PRIVATE_KEY: ${{secrets.EC2_SSH_KEY}}
              run: |
                echo "$PRIVATE_KEY" > ssh_key.pem && chmod 600 ssh_key.pem
                ssh -o StrictHostKeyChecking=no -i ssh_key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}
                rm ssh_key
            
                
                
                
        
